name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build:all

      - name: Build CSS
        run: npx parcel build src/css/main.css --out-dir dist
        
      - name: Copy CSS directly
        run: cp src/css/main.css dist/

      - name: Copy index.html to dist
        run: cp index.html dist/

      - name: Update CSS path in index.html
        run: sed -i 's|./src/css/main.css|./main.css|g' dist/index.html || true
        
      - name: Update CSS path in try.html
        run: sed -i 's|./src/css/main.css|./main.css|g' dist/try.html || true

      - name: Copy try.html to dist
        run: cp try.html dist/
        
      - name: Copy examples directory to dist
        run: cp -r examples dist/ || true
        
      - name: Copy docs directory to dist
        run: cp -r docs dist/ || true

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages